[project]
name = "introduction-to-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "suzzis", email = "116038356+suzzis@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "jupyter>=1.1.1",
    "minsearch>=0.2.0",
    "openai>=3.16.2",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
]

[project.scripts]
introduction-to-rag = "introduction_to_rag:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
